//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tip2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tip2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginForm.Resources.Tip2", typeof(Tip2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Այծեղջյուր` 22.12 – 20.01
        ///Ամենադժվար պահերին աջակցություն գտեք ընտանիքում:
        ///Ամենաուրախ պահերին մտերիմների հետ կիսեք ձեր ուրախությունը:
        ///Ընտանիքն ու տունը ձեր թիկունքն ու հիմքն են:
        ///Ջրհոս`  21.01 – 18.02
        ///Այդքան սենտիմենտալ մի եղեք:
        ///Ձեզնից սպասում են լուրջ ու պատասխանատու արարքներ:
        ///Արդյունքը միայն ձեզնից է կախված: Գործեք կամ մի բողոքեք այն բանից,
        /// որ դուք ոչինչ չունեք:
        ///Ձկներ` 19.02 – 20.03
        ///Ձեր բարությանն անպաման բարությամբ կպատասխանեն:
        ///Ամեն դեպքում արեք այն, ինչ ձեզ ձեր սիրտն է թելադրում:.
        /// </summary>
        internal static string Tip_2 {
            get {
                return ResourceManager.GetString("Tip_2", resourceCulture);
            }
        }
    }
}
